CREATE TABLE DEVICE_REGISTRATION
(
    UID     				VARCHAR(30)		PRIMARY KEY,
	NAME     				VARCHAR(50)		NOT NULL,
    DEVICE      			VARCHAR(150)	NOT NULL,
    ADDRESS     			VARCHAR(80)		NOT NULL,
    OWNER   				VARCHAR(40)		NOT NULL,
    BOT 					VARCHAR(40)		NOT NULL,
	TOKEN 					VARCHAR(250)	NOT NULL,
	CHATID 					VARCHAR(80)		NOT NULL,
	DATE					DATETIME 		NOT NULL
);